services:
  frontend-dev:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:8080"      # Vite default
    environment:
      - NODE_ENV=development
    command: sh -c "npm ci && npm run serve"

  frontend:
    image: "${IMAGE_URL}"
    container_name: "frontend-service"
    pull_policy: always
    expose:
      - "80"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost/" ]
      interval: 30s
      timeout: 3s
      retries: 3
    environment:
      - NODE_ENV=production
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_API_KEY=${VUE_APP_API_KEY}
    networks:
      - shared_network

networks:
  shared_network:
    external: true
