name: Code Scanning on PR to Dev

on:
  pull_request:
    branches: [ dev ]

jobs:
  code-scan:
    name: Code Scanning
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Run ESLint
        run: |
          npm ci
          npm run lint