name: Build & Publish Docker Image

on:
  push:
    branches: [ "prod" ]
    tags: [ "v*" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (optional for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Define tags
        id: meta
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/car-price-app
          echo "image=$IMAGE" >> $GITHUB_OUTPUT
          # Tag latest untuk branch main, dan tag sha untuk traceability
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "tags=$IMAGE:latest,$IMAGE:sha-${{ github.sha }}" >> $GITHUB_OUTPUT
          else
            echo "tags=$IMAGE:sha-${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # Multi-arch (opsional): linux/amd64,linux/arm64
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            # Suntik env build-time untuk Vue CLI (jika perlu)
            # VUE_APP_API_BASE_URL=${{ secrets.VUE_APP_API_BASE_URL }}
